//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Emergencies = new HashSet<Emergency>();
            this.Employee_Previous_Jobs = new HashSet<Employee_Previous_Jobs>();
            this.Internal_Employment_History = new HashSet<Internal_Employment_History>();
            this.Staff_Education = new HashSet<Staff_Education>();
            this.Staff_Leave = new HashSet<Staff_Leave>();
        }
    
        public int StaffId { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public string TRN { get; set; }
        public string NIS { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Postal_Code { get; set; }
        public string Parish { get; set; }
        public string Country { get; set; }
        public string Marital_Stuts { get; set; }
        public string Home_Number { get; set; }
        public string Mobile_Number { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Employment_Status { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> EmploymentStatusid { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergency> Emergencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Previous_Jobs> Employee_Previous_Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Internal_Employment_History> Internal_Employment_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Education> Staff_Education { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Leave> Staff_Leave { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee11 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual EmploymentStatu EmploymentStatu { get; set; }
    }
}
