//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Education
    {
        public int EducationId { get; set; }
        public string Institution_Name { get; set; }
        public System.DateTime Start_Year { get; set; }
        public string Graduation_Year { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> QualificationId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
