//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Leave
    {
        public int LeaveId { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
    
        public virtual Leave_Type Leave_Type { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
